{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "octelium.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "octelium.labels" . | nindent 4 }}
  {{- with (include "octelium.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "octelium.selectorLabels" . | nindent 6 }}
  {{- if ne (toString .Values.podDisruptionBudget.maxUnavailable) "" }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . | quote }}
  {{- end }}
{{- end }}
