{{- if include "octelium.createsSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "octelium.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "octelium.labels" . | nindent 4 }}
  {{- with (include "octelium.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  data: {{ .Values.octelium.auth.token | b64enc | quote }}
{{- end }}
