{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "octelium.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "octelium.labelsWith" (dict "ctx" . "extra" .Values.serviceAccount.labels) | nindent 4 }}
  {{- with (include "octelium.annotationsWith" (dict "ctx" . "extra" .Values.serviceAccount.annotations)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
