apiVersion: v2
name: octelium
description: Run the Octelium client in Kubernetes to connect Workloads to an Octelium Cluster, publish remote Services in-cluster and serve in-cluster Services to the Cluster
type: application
version: 1.0.1
appVersion: "0.43.0"
kubeVersion: ">=1.23.0-0"
icon: https://octelium.com/assets/logo-180-DUsurYDp.png
home: https://octelium.com
sources:
  - https://github.com/octelium/octelium
  - https://github.com/octelium/helm-charts
keywords:
  - octelium
  - zero-trust
  - ztna
  - vpn
  - wireguard
  - quic
  - networking
  - security
  - identity-aware-proxy
  - remote-access
maintainers:
  - name: George Badawi
    email: george@octelium.com
    url: https://octelium.com
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: octelium
      image: ghcr.io/octelium/octelium:0.43.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://octelium.com/docs
    - name: Chart source
      url: https://github.com/octelium/helm-charts/tree/main/charts/octelium
    - name: Octelium source
      url: https://github.com/octelium/octelium
    - name: Report an issue
      url: https://github.com/octelium/octelium/issues
  artifacthub.io/changes: |
    - kind: changed
      description: Updated the Octelium client from 0.42.0 to 0.43.0
