name: Helm Publish
permissions:
  contents: read
  packages: write
on:
  workflow_dispatch:
jobs:
  helm:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: octelium
          repository: ${{ github.repository_owner }}/helm-charts
          tag: 0.2.0
          path: charts/octelium
          registry: ghcr.io
          registry_username: ${{ github.repository_owner }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
